#!/usr/bin/env python3
"""Build the requirements traceability matrix and fail if it is not trustworthy.

Checks, in order:
  1. every automated test ID named in requirements.yml exists in the application repository's test sources
  2. every manual test ID named in requirements.yml exists in test-cases/manual-test-cases.csv, and that
     case names the same requirement
  3. every requirement has automated or manual coverage, or an explicit `external` note
Writes docs/TRACEABILITY.md. Exit code 1 if any check fails.

usage: traceability.py --app-repo PATH [--requirements FILE] [--manual FILE] [--out FILE]
"""
import argparse
import csv
import re
import sys
from collections import Counter
from pathlib import Path

import yaml

TEST_ID = re.compile(r"\bTC_[A-Z0-9]+(?:_[A-Z0-9]+)*_\d{3}\b")
SOURCE_SUFFIXES = {".js", ".ts", ".mjs"}
# a test declaration whose title starts with an id: test(...), test.fail(...), appTest(...)
TITLE = re.compile(r"""\b\w*[tT]est(?:\.\w+)?\(\s*['"`](TC_[A-Z0-9_]+?_\d{3})\b""")


def automated_ids(app_repo: Path) -> set[str]:
    """Every test ID declared in a test title of the application's test folders."""
    found: set[str] = set()
    for path in (app_repo / "client" / "tests").rglob("*"):
        if path.suffix in SOURCE_SUFFIXES and path.is_file():
            found.update(TITLE.findall(path.read_text(encoding="utf-8")))
    return found


def load_manual(path: Path) -> dict[str, dict]:
    with path.open(newline="", encoding="utf-8") as handle:
        return {row["ID"]: row for row in csv.DictReader(handle)}


def check(requirements: list[dict], automated: set[str], manual: dict[str, dict]) -> list[str]:
    errors: list[str] = []
    seen: set[str] = set()
    for req in requirements:
        rid = req["id"]
        if rid in seen:
            errors.append(f"{rid}: duplicate requirement id")
        seen.add(rid)
        for tid in req.get("automated", []):
            if tid not in automated:
                errors.append(f"{rid}: automated test {tid} was not found in the application repository")
        for mid in req.get("manual", []):
            case = manual.get(mid)
            if case is None:
                errors.append(f"{rid}: manual case {mid} is not in the manual test case file")
            elif case["Requirement"] != rid:
                errors.append(f"{rid}: manual case {mid} belongs to {case['Requirement']}")
        if not (req.get("automated") or req.get("manual") or req.get("external")):
            errors.append(f"{rid}: no coverage and no external note")
    return errors


def render(requirements: list[dict], automated: set[str], manual: dict[str, dict]) -> str:
    used = {t for r in requirements for t in r.get("automated", [])}
    suites = Counter(re.sub(r"_\d{3}$", "", t) for t in used)
    lines = [
        "# Requirements traceability matrix",
        "",
        "Generated by `tools/traceability.py` from `requirements.yml`. Do not edit by hand.",
        "",
        "| Requirement | Risk | Automated | Manual cases | Other | Status |",
        "|---|---|---|---|---|---|",
    ]
    for req in requirements:
        auto, man = req.get("automated", []), req.get("manual", [])
        status = "Automated" if auto else ("Manual only" if man else "External")
        if auto and man:
            status = "Automated + manual"
        lines.append(
            f"| {req['id']} | {req.get('risk', '')} | {len(auto)} | {', '.join(man) or '-'} | "
            f"{'yes' if req.get('external') else '-'} | {status} |"
        )
    never = sorted(automated - used)
    lines += [
        "",
        f"**{len(requirements)} requirements**, {len(used)} of {len(automated)} automated tests linked to a requirement, "
        f"{len({m for r in requirements for m in r.get('manual', [])})} of {len(manual)} manual cases linked.",
        "",
        "## Automated tests by suite (linked)",
        "",
        "| Suite | Tests |",
        "|---|---|",
        *[f"| {suite} | {count} |" for suite, count in sorted(suites.items())],
    ]
    if never:
        lines += ["", "## Automated tests not linked to any requirement", "", ", ".join(f"`{t}`" for t in never),
                  "", "These need a requirement, or they test something nobody asked for."]
    unlinked_manual = sorted(set(manual) - {m for r in requirements for m in r.get("manual", [])})
    if unlinked_manual:
        lines += ["", "## Manual cases not linked from any requirement", "", ", ".join(unlinked_manual)]
    ext = [r for r in requirements if r.get("external")]
    if ext:
        lines += ["", "## Covered outside the application repository", ""]
        lines += [f"- **{r['id']}**: {r['external']}" for r in ext]
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    root = Path(__file__).resolve().parent.parent
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--app-repo", type=Path, required=True, help="checkout of the application (the Ecom repository)")
    ap.add_argument("--requirements", type=Path, default=root / "requirements.yml")
    ap.add_argument("--manual", type=Path, default=root / "test-cases" / "manual-test-cases.csv")
    ap.add_argument("--out", type=Path, default=root / "docs" / "TRACEABILITY.md")
    args = ap.parse_args(argv)

    requirements = yaml.safe_load(args.requirements.read_text(encoding="utf-8"))["requirements"]
    automated = automated_ids(args.app_repo)
    manual = load_manual(args.manual)
    errors = check(requirements, automated, manual)
    args.out.write_text(render(requirements, automated, manual), encoding="utf-8")
    for e in errors:
        print(f"ERROR: {e}", file=sys.stderr)
    print(f"{len(requirements)} requirements, {len(automated)} automated tests found, {len(manual)} manual cases, {len(errors)} problems")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
